import { NextResponse } from "next/server"

const products = [
  {
    id: 1,
    name: "Classic White Tee",
    description: "Soft cotton everyday t-shirt.",
    price: 19.99,
    currency: "USD",
    category: "Apparel",
    brand: "Northline",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/55/T-shirt.png",
    stock: 42,
    rating: 4.6,
  },
  {
    id: 2,
    name: "Running Sneakers",
    description: "Lightweight sneakers for daily runs.",
    price: 74.99,
    currency: "USD",
    category: "Footwear",
    brand: "Stride",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Running_shoes.jpg",
    stock: 18,
    rating: 4.4,
  },
  {
    id: 3,
    name: "Leather Wallet",
    description: "Slim genuine leather wallet.",
    price: 29.5,
    currency: "USD",
    category: "Accessories",
    brand: "Brownbay",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Leather_wallets_01.JPG",
    stock: 65,
    rating: 4.8,
  },
  {
    id: 4,
    name: "Wireless Headphones",
    description: "Over-ear headphones with deep bass.",
    price: 129.0,
    currency: "USD",
    category: "Electronics",
    brand: "Pulse",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Headphones.jpg",
    stock: 24,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Ceramic Mug",
    description: "Minimal mug for coffee or tea.",
    price: 12.99,
    currency: "USD",
    category: "Home",
    brand: "Stillhouse",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/8/87/Mug.jpg",
    stock: 80,
    rating: 4.5,
  },
  {
    id: 6,
    name: "Desk Lamp",
    description: "Compact LED lamp with warm light.",
    price: 39.99,
    currency: "USD",
    category: "Home",
    brand: "Glowist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/A_desk_lamp.jpg",
    stock: 31,
    rating: 4.3,
  },
  {
    id: 7,
    name: "Smart Watch",
    description: "Fitness tracking and notifications.",
    price: 149.99,
    currency: "USD",
    category: "Electronics",
    brand: "Orbit",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Smart_Watch.jpg",
    stock: 27,
    rating: 4.2,
  },
  {
    id: 8,
    name: "Backpack",
    description: "Durable backpack with laptop sleeve.",
    price: 54.0,
    currency: "USD",
    category: "Bags",
    brand: "Trailform",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Backpack_%2826645453056%29.jpg",
    stock: 36,
    rating: 4.6,
  },
  {
    id: 9,
    name: "Bluetooth Speaker",
    description: "Portable speaker with clear sound.",
    price: 59.99,
    currency: "USD",
    category: "Electronics",
    brand: "EchoBeat",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Bluetooth_Speaker.jpg",
    stock: 14,
    rating: 4.7,
  },
  {
    id: 10,
    name: "Sunglasses",
    description: "UV-protected lightweight sunglasses.",
    price: 24.99,
    currency: "USD",
    category: "Accessories",
    brand: "Sunry",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/92/Sunglasses.png",
    stock: 52,
    rating: 4.4,
  },
]

export async function GET() {
  return NextResponse.json(products)
}
